spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: xn123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibername:
        dialect: org.hibername.dialect.MySQL5Dialect
  data:
    mongodb:
      uri: mongodb://shandai:fzcfQwuMH2q@106.15.156.61:27017/risk
